[advisories]
vulnerability = "deny"
unsound       = "deny"
yanked        = "warn"
unmaintained  = "warn"
notice        = "warn"
ignore        = []

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Zlib",
  "BSL-1.0",
  "Unicode-3.0",
  "Apache-2.0 WITH LLVM-exception"
]
confidence-threshold = "high"
unlicensed = "deny"
copyleft   = "deny"
default    = "deny"

[[licenses.clarify]]
name = "version_check"
version = "0.9.5"
expression = "MIT OR Apache-2.0"
license-files = []

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git      = "deny"
allow-registry   = ["https://github.com/rust-lang/crates.io-index"]
