[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "BSL-1.0",
  "Unicode-3.0",
  "Apache-2.0 WITH LLVM-exception"
]
confidence-threshold = 0.92

[[licenses.clarify]]
name = "version_check"
version = "0.9.5"
expression = "MIT OR Apache-2.0"
license-files = []
